### ISSUE TITLE
Suggestion box renders under Chat

### ISSUE THREAD

**Issue by ThatCuteOne** [Oiha-dev/Lexikon#3]
I am using the version 1.0.0 for 1.21, with only the mod and its dependencies installed.
basically the text from the vanilla chatbox renders over the suggestion box from Lexikon.
Here an example:
![2024-10-02_23 59 03](https://github.com/user-attachments/assets/3474c90b-ffae-49e3-812c-0cd2d7f45ad3)

**Comment by Oiha-dev** [comment]
I think It's due to the fact that Mojang Update the code for the chat in 1.20.6 (if I'm correct) and my mixin doesn't for the same way, I will try to look into it for the next update, but thanks for letting me know

**Comment by Oiha-dev** [comment]
Fixed on GitHub, It will be in the next update for modrinth and curseforge
